name: export-and-branch-solution-spn
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: CuraleafEdgeEmpMetrics
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions

permissions:
  contents: write
  
jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ secrets.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.POWER_PROD_SPN_CLIENT_ID }}
        client-secret: ${{ secrets.POWER_PROD_SPN_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        # cloud: ${{ inputs.CLOUD_TYPE }}

    - uses: actions/checkout@v3
      # with:
      #   lfs: true        

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.POWER_PROD_SPN_CLIENT_ID }}
        client-secret: ${{ secrets.POWER_PROD_SPN_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    # - name: Publish Solution
    #   uses: microsoft/powerplatform-actions/publish-solution@v1
    #   with:
    #     environment-url: ${{ secrets.BUILD_ENVIRONMENT_URL }}
    #     app-id: ${{ secrets.POWER_PROD_SPN_CLIENT_ID }}
    #     client-secret: ${{ secrets.POWER_PROD_SPN_CLIENT_SECRET }}
    #     tenant-id: ${{ secrets.AAD_TENANT_ID }}

    # - uses: actions/checkout@v4
    # - name: Create Placeholder File
    #   run: |
    #      mkdir ${{ github.event.inputs.solution_target_folder}}
    #      touch ${{ github.event.inputs.solution_target_folder}}/.gitkeep

    # - name: Stage and Commit
    #   run: |
    #      git add ${{ github.event.inputs.solution_target_folder}}
    #      git commit -m "Create target_folder"   

    # - name: Push Changes (Optional)
    #   run: |
    #       git push origin main         

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        # solution_name: ${{ github.event.inputs.solution_name }}
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        # target_branch: main
        allow-empty-commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
