name: Export CuraleafEdgeEmpMetrics Solution
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on: 
   workflow_dispatch:      

jobs:
  Export-CuraleafEdgeEmpMetrics-Solution:
    uses: ./.github/workflows/export-solution-reusable.yml
    with:
      # You can specify the solution name here
      SOLUTION_NAME: CuraleafEdgeEmpMetrics
      # Update your actual cloud instance here (Public, UsGov, UsGovHigh, UsGovDoD)
      CLOUD_TYPE: 'Public'
    secrets:
      AAD_APP_SECRET: ${{ secrets.POWER_PROD_SPN_CLIENT_SECRET }}
      AAD_CLIENT_ID: ${{ secrets.POWER_PROD_SPN_CLIENT_ID }}
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      DEV_ENVIRONMENT_URL: ${{ secrets.DEV_ENVIRONMENT_URL }}
